apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
  labels:
    app: snake-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game-container
        image: snake-game:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
