apiVersion: apps/v1
kind: Service
metadata:
  name: snake-game-service
  labels:
    app: snake-game
spec:
  selector:
    app: snake-game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer